CREATE TABLE [dbo].[ATMs]
(
	[Id] INT NOT NULL IDENTITY(100000, 1),
	[Name] NVARCHAR(2048) NOT NULL,
	[BankId] INT NOT NULL,
	[CreatedDate] DATETIME NULL,
	[UpdatedDate] DATETIME NULL,
	[IsDeleted] BIT NOT NULL DEFAULT(0),
	CONSTRAINT PK_ATMs_ID PRIMARY KEY ([Id]),
	CONSTRAINT FK_ATMs_BankId FOREIGN KEY ([BankId]) REFERENCES [dbo].[Banks]([Id])

)
